### ISSUE TITLE
i-bem: fix getMod jsDoc

### ISSUE THREAD

**Issue by aristov** [bem/bem-core#1027]
[As described in jsDoc](https://github.com/bem/bem-core/blob/v2/common.blocks/i-bem/i-bem.vanilla.js#L299) `getMod` returns strings only. But it returns boolean `true` for existing boolean modifier. It seems that we should fix jsDoc by adding `Boolean` type to the list of returned value types.
Yet another unclear thing is why `getMod` [returns an empty string](https://github.com/bem/bem-core/blob/v3/common.blocks/i-bem/i-bem.spec.js#L130) for missing (`false`) modifier, when boolean `false` is expected? Should we fix this behaviour too, or is there any reason why it works so?

**Comment by qfox** [comment]
:+1: 

`false` shouldn't be returned since boolean modifiers either exists or doesn't. Not sure what it returns atm, but it should be the same as `getMod` call on non-set modifier. imo.

**Comment by dfilatov** [comment]
I can't understand how you want to determine if a modifier is a boolean or not in runtime, especially when it wasn't set before.

**Comment by qfox** [comment]
> especially when it wasn't set before.

That's why it should return default value if mod isn't set.

**Comment by aristov** [comment]
Can we assume that we have boolean modifiers which value is `true` or `false` and multi-value modifiers that might have a set of string values, or boolean `false` if it's not specified?

**Comment by qfox** [comment]
@aristov :+1: Good for me.

**Comment by dfilatov** [comment]
I haven't seen why this solution is better. There's no value `false`, there's no modifier at all.
If you know you deal with boolean modifier you can use `hasMod` which always returns boolean.

**Comment by qfox** [comment]
@dfilatov Modifier doesn't exist by default and `false` value means that modifier is not set. Another option is `null`.
Imagine you need to store state of block/elem instance to revive it later: what common data you need to store? `{block, elem, mods, params, ...}`.

p.s. `hasMod` is nice method, but I don't see a purpose of it (since boolean modifiers was implemented).

**Comment by qfox** [comment]
I'd say:
- "As described in jsDoc getMod returns strings only" — just add `boolean` to jsdoc
- "why getMod returns an empty string for missing" — let's decide what it should be
  - `false` since modifier isn't set
  - `null` if you don't like `false` — then we should add `?` to the front in jsdoc.

Also the second part can make code cleaner.

Another thing: we can think about declaring modifier types explicitly somewhere, and, for BC, use `string` by default. It could help to make complex modifiers.

**Comment by veged** [comment]
we can't use complex types for modifiers because of "multilingual" nature of BEM — we need to support those modifiers values on filesystem, CSS and so on

so I confidently believe in empty string as only possible value for unset modifier

**Comment by qfox** [comment]
@veged actually, serialization + deserialization is the key here.

And I don't see why you closed it. It returns `true` in some cases so will be better to add Boolean to type.

**Comment by aristov** [comment]
@zxqfox could you make PR, please?

**Comment by aristov** [comment]
Landed with #1063 and need to port it to v3
