### ISSUE TITLE
i18n: Introduce current lang getter

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1194]
New implementation of `i18n` lacks possibility to get current language id which is quite useful at least for static projects. Let's add it?

// cc @veged @narqo @aristov @blond

**Comment by blond** [comment]
:+1: 

Maybe add `lang` argument to [decl](https://github.com/bem/bem-core/blob/v2/common.blocks/i18n/i18n.i18n.js#L23) method?

``` js
var core = /* ... */,
    keysets = {
        greeting: {
            hello: "Привет!"
        }
    },
    i18n = core().decl(keysets, 'ru');

i18n('greeting', 'hello'); // Привет!
i18n.lang // ru
```

**Comment by narqo** [comment]
@tadatuta "Current" language in `BEM.I18N` should really be considered as a bug, not as a feature. As static HTML generation is the only case where it can be applied. You really can't use it in cases with dynamic HTML generation, because I18N is not attached to the context of the request, despite the fact this is the only thing it must be attached to. There is absolutely no safe way to call `setLang()` without additional workarounds on services :(

For static projects its not a problem to have static keysets with all "currents" you need:

``` js
// blocks/project/project.i18n/ru.js
module.exports = {
  "project" : {
    "lang" : "ru"
  }
}

// blocks/project/project.i18n/en.js
module.exports = {
  "project" : {
    "lang" : "en"
  }
}

// blocks/project/project.js
i18n('project', 'lang'); // "ru" | "en"
```

**Comment by tadatuta** [comment]
@narqo are you against to provide generic way to get language id in new `i18n` implementation which doesn't have possibility to switch it in runtime anyways? to use simple `i18n.lang()` instead of hack with custom keys?

**Comment by narqo** [comment]
@tadatuta to have such getter, you need to store the language somewhere, so the API should be slighty changed as @blond suggested, but I don't like such declaration `i18n.decl(keysets, currentLanguage)`. And I don't understand how this getter should change it's value in non-static projects if it doesn't have setter API.
