### ISSUE TITLE
i-bem-dom: Allow `_domEvents` working with arbitrary jQuery-chain

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#1386]
Looks like `_domEvents` doesn't work with arbitrary jQuery-chain. But it's needed, see: https://github.com/bem/bem-components/blob/v5/common.blocks/popup/_target/popup_target_anchor.js#L200

**Comment by tadatuta** [comment]
Seems like it was done intentionally and `_domEvents` can only be bind to `window`, `document` or block instances: https://github.com/bem/bem-core/blob/v4/common.blocks/i-bem-dom/__events/i-bem-dom__events.js#L272

So what's the way to bind to arbitrary DOM node?

BTW, why an error is thrown only for jquery chain with just one element?

**Comment by veged** [comment]
Originally we were going to disallow bind to arbitrary jQuery-chain for prevent direct DOM-binds to internals of other entities (like `this._domEvents(otherBlock.domElem).on(...)`). But since we can manage unbinds properly and cases like [`popup_target_anchor`](https://github.com/bem/bem-components/blob/v5/common.blocks/popup/_target/popup_target_anchor.js#L200) we have decided to make it possible.
