### ISSUE TITLE
Add local jquery fallback when no internet connection

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-core#512]
Now `jquery` is the only external resource which makes it impossible to develop locally without internet connection.

I suggest to:
1. Fire `fail` callback in `loader` if resource wasn't loaded
2. Commit `jquery` library inside `bem-core` as a fallback

**Comment by narqo** [comment]
> [..] external resource which makes it impossible to develop locally without internet connection

You can insert you local copy of jQuery into a global scope, so `jquery` module [would use it](https://github.com/bem/bem-core/blob/v2/common.blocks/jquery/jquery.js#L21) instead of loading it via `loader`. 

It would be much easier than try to answer questions like 1) "why do I have jQuery file inside my bundle?" 2) "why do you use jQuery from `loader` instead of one from question (1)?

**Comment by tadatuta** [comment]
That's clear but it that case you need to switch manually each time.
But I won't insist if everybody thinks it's not convenient.
